title: Xiaotong (Olivia) Liu
#logo: /assets/img/headshot_circle.png
description: Data Analyst Intern @SDTC, Data Science Research Assistant @Unity Health Toronto| Master of Engineering @University of Toronto
show_downloads: false
theme: jekyll-theme-minimal
