title: Xiaotong (Olivia) Liu
logo: asset/Screen Shot 2023-10-10 at 5.09.52 PM.png
description: Data Analyst Intern @SDTC, Data Science Research Assistant @Unity Health Toronto| Master of Engineering @University of Toronto
show_downloads: false
theme: jekyll-theme-minimal
